# Generated by Django 2.0.5 on 2018-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0012_auto_20180917_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
    ]
